import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { fetchAPI } from "./utils/fetch-api";
import Navbar from "./components/NavBar";
import { FALLBACK_GLOBAL, FALLBACK_SEO } from "./utils/constants";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

async function getGlobal(): Promise<any> {
  // const token = process.env.NEXT_PUBLIC_STRAPI_API_TOKEN;

  // if (!token) throw new Error("The Strapi API Token environment variable is not set.");

  const path = `/global`;
  // const options = { headers: { Authorization: `Bearer ${token}` } };

  const urlParamsObject = {
    populate: [
      "metadata.shareImage",
      "favicon",
      "notificationBanner.link",
      "navbar.links",
      "navbar.navbarLogo.logoImg",
      "footer.footerLogo.logoImg",
      "footer.menuLinks",
      "footer.legalLinks",
      "footer.socialLinks",
      "footer.categories",
    ],
  };
  return await fetchAPI(path, urlParamsObject);
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
  const meta = await getGlobal();

  if (!meta.data) return FALLBACK_SEO;

  const { metadata, favicon } = meta.data.attributes;
  const { url } = favicon.data.attributes;

  return {
    title: metadata.metaTitle,
    description: metadata.metaDescription,
    // icons: {
    //   icon: [new URL(url, getStrapiURL())],
    // },
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const global = await getGlobal();
  // if (!global.data) return null;

  // const { notificationBanner, navbar, footer } = global.data.attributes;
  // const navbarLogoUrl = getStrapiMedia(
  //   navbar.navbarLogo.logoImg.data.attributes.url
  // );
  const navbarLogoUrl = null;

  // const footerLogoUrl = getStrapiMedia(
  //   footer.footerLogo.logoImg.data.attributes.url
  // );
  const footerLogoUrl = null;

  const { navbar, footer } = FALLBACK_GLOBAL.data.attributes;

  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        <Navbar
          links={navbar.links}
          logoUrl={navbarLogoUrl}
          logoText={navbar.navbarLogo.logoText}
        />

        <main className="min-h-screen overflow-x-hidden px-2">{children}</main>

        {/* <Banner data={notificationBanner} /> */}

        <Footer
          logoUrl={footerLogoUrl}
          logoText={footer.footerLogo.logoText}
          menuLinks={footer.menuLinks}
          categoryLinks={footer.categories.data}
          legalLinks={footer.legalLinks}
          socialLinks={footer.socialLinks}
        />
      </body>
    </html>
  );
}
